2024-03-15 20:27:27,483 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:96]
2024-03-15 20:27:53,275 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:96]
2024-03-15 20:28:09,682 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:96]
2024-03-15 20:28:24,435 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:96]
2024-03-15 20:31:38,170 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-15 20:31:49,372 INFO: User with id:2 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:66]
2024-03-15 20:37:00,049 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-15 20:37:15,321 INFO: User with id:2 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:67]
2024-03-15 21:37:18,970 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-15 21:38:16,661 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-15 21:38:38,813 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-15 21:43:47,666 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-15 21:43:58,050 INFO: User with id:2 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:67]
2024-03-15 21:44:40,820 INFO: User with id:9 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:67]
2024-03-15 21:56:08,351 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-15 21:56:40,696 INFO: User with id:10 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:68]
2024-03-15 21:59:20,475 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-15 22:00:34,356 INFO: User with id:11 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:68]
2024-03-15 22:04:01,559 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-16 14:43:41,025 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-16 14:44:01,416 INFO: User with id:2 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:62]
2024-03-16 14:46:16,437 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-16 14:46:37,234 INFO: User with id:9 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:62]
2024-03-16 14:47:04,606 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-16 14:47:59,531 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-16 14:48:40,337 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-16 14:48:52,501 INFO: User with id:2 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:62]
2024-03-16 14:50:27,184 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-16 14:51:23,248 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-16 14:51:35,455 INFO: User with id:2 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:62]
2024-03-16 14:52:01,407 INFO: User with id:9 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:62]
2024-03-16 14:54:54,797 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-16 14:55:36,799 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:97]
2024-03-16 14:55:51,620 INFO: User with id:9 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:62]
2024-03-16 14:56:08,325 INFO: Failed login attempt. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:76]
2024-03-16 15:14:19,933 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:106]
2024-03-16 15:14:39,681 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:106]
2024-03-16 15:14:42,993 ERROR: Exception on /auth/login [GET] [in C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\app\auth\routes.py", line 55, in login
    new_captcha_dict = Captcha.create()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask_simple_captcha\captcha_generation.py", line 108, in create
    text = gen_captcha_text(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask_simple_captcha\utils.py", line 157, in gen_captcha_text
    return ''.join((random.choice(charpool) for _ in range(length)))
                                                     ^^^^^^^^^^^^^
TypeError: 'tuple' object cannot be interpreted as an integer
2024-03-16 15:15:01,304 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:106]
2024-03-16 15:15:51,854 INFO: User with id:2 successfully logged in. [in C:\Users\Arman\Documents\flask_project\app\auth\routes.py:66]
2024-03-16 15:16:18,937 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:106]
2024-03-16 15:16:26,515 ERROR: Exception on /auth/login [GET] [in C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\app\auth\routes.py", line 55, in login
    new_captcha_dict = Captcha.create()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask_simple_captcha\captcha_generation.py", line 108, in create
    text = gen_captcha_text(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Arman\Documents\flask_project\venv\Lib\site-packages\flask_simple_captcha\utils.py", line 157, in gen_captcha_text
    return ''.join((random.choice(charpool) for _ in range(length)))
                                                     ^^^^^^^^^^^^^
TypeError: 'tuple' object cannot be interpreted as an integer
2024-03-16 15:20:05,272 INFO: Application startup [in C:\Users\Arman\Documents\flask_project\app\__init__.py:106]
